site_name: Collections
site_description: Collections of Computer Science and Technology
repo_url: https://github.com/Slapaf/HUST-CS
copyright: Copyright © 2023 HUST-211
theme:
      name: material
      language: zh
      features:
            - header.autohide
nav:
      - 主页: index.md
      - 开发:
              - Docker: develop/docker.md
              - DevOps: develop/devops.md
              - MPI: develop/mpi.md
      - 语言:
              - CMake: languages/cmake.md
              - CPP: languages/cpp.md
              - CUDA: languages/cuda.md
              - Python: languages/python.md
      - 研究:
              - Distributed: research/distributed.md
              - GPT: research/gpt.md
              - Paper: research/papers.md
      - 系统:
              - Tools: system/tools.md
              - Linux: system/linux.md
              - Windows: system/windows.md
      - 其他:
              - Games: others/games.md
              - OpenSource: others/opensource.md
              - Unknown: others/unknown.md
plugins:
      - tags:
              enabled: true
      - search
      - glightbox:
              touchNavigation: true
              loop: false
              effect: zoom
              slide_effect: slide
              width: "100%"
              height: auto
              zoomable: true
              draggable: true
              auto_caption: false
              caption_position: bottom
markdown_extensions:
      - admonition
      - attr_list
      - md_in_html
      - toc:
              permalink: "#"
      - pymdownx.highlight:
              anchor_linenums: true
